DROP FUNCTION IF EXISTS FindUserById;

DELIMITER $$

CREATE FUNCTION FindUserByID(id int) RETURNS VARCHAR(20)
BEGIN
    DECLARE RESULT VARCHAR(20) DEFAULT 'No user with this ID';
    SET RESULT = (SELECT LASTNAME FROM READERS WHERE READER_ID = id);
	IF RESULT IS NULL THEN
		SET result = 'No user with this ID';
	END IF;	
        return RESULT;
END $$

DELIMITER ;

SELECT FindUserById(4) AS READERS;