CREATE TABLE STATS(
	STAT_ID INT(11) NOT NULL AUTO_INCREMENT,
    STAT_DATE DATETIME NOT NULL,
    STAT VARCHAR(20) NOT NULL,
    VALUE INT(11) NOT NULL,
    PRIMARY KEY (STAT_ID)
);

CREATE VIEW BESTSELLERS_COUNT AS
	SELECT COUNT(BOOKS.BESTSELLER) AS QUANITY FROM books WHERE BOOKS.BESTSELLER = true;
    

DELIMITER $$

CREATE EVENT UPDATE_BESTSELLERS
	ON SCHEDULE EVERY 10 SECOND 
    DO BEGIN
    
	CALL UpdateBestsellers();
	INSERT INTO STATS (STAT_DATE, STAT, VALUE) VALUES (CURRENT_TIMESTAMP, "Bestsellers", (SELECT * FROM BESTSELLERS_COUNT));
	COMMIT;
    
    END $$
DELIMITER ;


